name: Deploy
on: 
  workflow_dispatch:
  schedule:
    - cron:  '30 5,17 * * *'
jobs:
  UpdateUsername:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2.3.0
      with:
        node-version: 12
        cache: 'npm'
    - name: Install Deps
      run: npm install
    - name: Update Username
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GITHUB: ${{ secrets.GITHUB }}
      run: npm run start
