name: SyncContentAndUsername
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 12,0 * * *'
jobs:
  UpdateData:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2.3.4
    - name: Use Ruby and Install Dependencies
      uses: ruby/setup-ruby@v1.84.0
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - name: Update data
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GITHUB: ${{ secrets.GITHUB }}
      run: bundler exec rake
