name: Update
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 12,0 * * *'
jobs:
  UpdateUsername:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2.3.4
    - name: Use Ruby 3.0.2
      uses: ruby/setup-ruby@v1.84.0
      with:
        ruby-version: 3.0.2
    - name: Update Username
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: bundler exec rake
